name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05

    - name: Setup Haskell environment using Nix
      run: nix-shell server/mergeCal.hs server/da1.ics server/da2.ics > server/index.html --command "echo Haskell environment setup"

    - name: Compile Haskell script
      run: nix-shell server/mergeCal.hs server/da1.ics server/da2.ics > server/index.html --command "ghc -o mergeCal-exe server/mergeCal.hs"

    - name: Upload compiled executable
      uses: actions/upload-artifact@v2
      with:
        name: mergeCal-exe
        path: ./mergeCal-exe server/da1.ics server/da2.ics > server/index.html
