name: Run Nix Shell

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v14

    - name: Run nix-shell on mergeCal.hs
      run: nix-shell server/mergeCal.hs
