name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05

    - name: Compile Haskell script
      run: nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [ pkgs.blaze-html pkgs.split pkgs.regex-tdfa pkgs.iso8601-time])" --run "ghc -o mergeCal server/mergeCal.hs"

    - name: Run compiled script with arguments
      run: ./mergeCal ./da1.ics ./da2.ics > index.html
