name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05

    - name: Prepare environment
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        nix-shell --run "ghc --version"

    - name: Compile Haskell Script
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        nix-shell --run "ghc -o mergeCal server/mergeCal.hs"
