name: Haskell-Nix CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      run: |
        sh <(curl -L https://nixos.org/nix/install) --daemon

    - name: Build and run using Nix
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh && nix-shell server/mergeCal.hs

    - name: Run the script (if required)
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh && ./server/mergeCal.hs
