name: Haskell Build

on:
  push:
    paths:
      - 'server/mergeCal.hs'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Haskell Stack
      uses: freckle/stack-setup-action@v2

    - name: Build with Stack
      run: |
        stack new my-project
        mv server/mergeCal.hs my-project/src/Main.hs
        cd my-project
        stack setup
        stack build

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: mergeCal-binary
        path: my-project/.stack-work/install/x86_64-linux/*/lts-*/bin/
